//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSolution.WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingPlace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParkingPlace()
        {
            this.ParkingPlaceReservation = new HashSet<ParkingPlaceReservation>();
            this.PaymentHistory = new HashSet<PaymentHistory>();
        }
    
        public int Id { get; set; }
        public int ParkingId { get; set; }
        public string CarType { get; set; }
    
        public virtual Parking Parking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParkingPlaceReservation> ParkingPlaceReservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHistory> PaymentHistory { get; set; }
    }
}
